[WIP]update Zone
vesoft-inc/nebula-docs-cn pull request #1338
Opened 2021-12-23 05:56 UTC by cooper-lzy

2022-01-10 01:47 UTC, cooper-lzy commented
https://github.com/vesoft-inc/nebula/pull/3343/files

2022-01-10 02:43 UTC, cooper-lzy commented
https://github.com/vesoft-inc/nebula/pull/3444

2022-01-10 07:50 UTC, darionyaphet commented on docs-2.0/2.quick-start/4.nebula-graph-crud.md
> +ADD HOSTS <ip>:<port> [,<ip>:<port> ...] [INTO NEW ZONE "<new_zone_name>"];
还有个命令是 ADD HOSTS <ip>:<port> [,<ip>:<port> ...] [INTO ZONE "<new_zone_name>"];

2022-01-10 07:58 UTC, darionyaphet commented on docs-2.0/3.ngql-guide/9.space-statements/1.create-space.md
> +|`<new_graph_space_name>`|目标图空间名称。该图空间必须未创建。图空间名称支持 1~4 字节的 UTF-8 编码字符，包括英文字母（区分大小写）、数字、中文等，但是不包括除下划线外的特殊字符。使用保留关键字时，需要用反引号（\`）包围，详情参见[关键字和保留字](../../3.ngql-guide/1.nGQL-overview/keywords-and-reserve
Edge type => EdgeType ?

2022-01-10 08:03 UTC, whitewum requested changes

2022-01-10 08:03 UTC, whitewum commented on docs-2.0/2.quick-start/4.nebula-graph-crud.md
> +    从 3.0 版本开始，在配置文件中添加的 Storage 节点无法直接使用，仅将节点信息存储在 Meta 服务中，需要使用`ADD HOSTS`命令将节点加入集群，才能正常使用。
从 3.0 版本开始，在配置文件中添加的 Storage 节点无法直接使用，配置文件的作用仅仅是将节点注册在 Meta 服务中。但是，必须使用 `ADD HOSTS` 命令后，才能正常读写 Storage 节点。

2022-01-10 08:03 UTC, whitewum commented on docs-2.0/4.deployment-and-installation/5.zone.md
> +    从 3.0 版本开始，在配置文件中添加的 Storage 节点无法直接使用，仅将节点信息存储在 Meta 服务中，需要使用`ADD HOST`命令将节点加入集群，才能正常使用。
ditto

2022-01-10 08:03 UTC, whitewum commented on docs-2.0/2.quick-start/4.nebula-graph-crud.md
> +    从 3.0 版本开始，在配置文件中添加的 Storage 节点无法直接使用，仅将节点信息存储在 Meta 服务中，需要使用`ADD HOSTS`命令将节点加入集群，才能正常使用。
请务必把如果没有ADD HOSTS的报错添加到FAQ中。

2022-01-10 08:24 UTC, cooper-lzy commented on docs-2.0/3.ngql-guide/9.space-statements/1.create-space.md
> +|`<new_graph_space_name>`|目标图空间名称。该图空间必须未创建。图空间名称支持 1~4 字节的 UTF-8 编码字符，包括英文字母（区分大小写）、数字、中文等，但是不包括除下划线外的特殊字符。使用保留关键字时，需要用反引号（\`）包围，详情参见[关键字和保留字](../../3.ngql-guide/1.nGQL-overview/keywords-and-reserve
文档都是分开写的

2022-01-10 08:25 UTC, cooper-lzy commented on docs-2.0/2.quick-start/4.nebula-graph-crud.md
> +    从 3.0 版本开始，在配置文件中添加的 Storage 节点无法直接使用，仅将节点信息存储在 Meta 服务中，需要使用`ADD HOSTS`命令将节点加入集群，才能正常使用。
这里是固定从3.0开始，用宏的话，下个版本变成从3.1版本开始了。

2022-01-10 08:38 UTC, cooper-lzy commented on docs-2.0/2.quick-start/4.nebula-graph-crud.md
> +    从 3.0 版本开始，在配置文件中添加的 Storage 节点无法直接使用，仅将节点信息存储在 Meta 服务中，需要使用`ADD HOSTS`命令将节点加入集群，才能正常使用。
报错信息暂时无法定位这个错误，提交了一个issue：https://github.com/vesoft-inc/nebula/issues/3675

2022-01-10 11:22 UTC, abby-cyber submitted a review, later dismissed

2022-01-10 11:22 UTC, abby-cyber commented on docs-2.0/4.deployment-and-installation/5.zone.md
> +    正在使用的 Storage 节点无法直接删除，需要先删除关联的图空间，才能删除 Storage 节点。
```suggestion
    无法直接删除正在使用的 Storage 节点，需要先删除关联的图空间，才能删除 Storage 节点。
```

2022-01-10 11:22 UTC, abby-cyber commented on docs-2.0/4.deployment-and-installation/5.zone.md
> +从集群中删除 Storage 节点。
是不是改成从Zone中删除Storage节点才能和本文的Zone主题挂上勾？

2022-01-10 11:22 UTC, abby-cyber commented on docs-2.0/4.deployment-and-installation/5.zone.md
> +将 Zone 中的所有 Storage 节点分离至多个新建 Zone。
是将同一个Zone中的所有Storage节点分离至多个将新建的Zone中，还是将多个Zone中的所有Storage节点xxx？

因为本文多次出现一个zone和多个zone，这里建议明确下。

2022-01-10 11:22 UTC, abby-cyber commented on docs-2.0/4.deployment-and-installation/5.zone.md
> +# 管理集群（Zone）
为什么不直接【管理 Zone】既然本文描述的都是和Zone相关的内容？这个标题会让我想到还有其他的类似文档，如管理集群（Graph）/管理集群（Storage）等。

2022-01-11 02:54 UTC, cooper-lzy commented on docs-2.0/4.deployment-and-installation/5.zone.md
> +从集群中删除 Storage 节点。
这个是从集群删除host，后面在想要必须add host，show hosts也看不到了

2022-01-11 03:20 UTC, whitewum approved these changes

2022-01-11 03:23 UTC, abby-cyber approved these changes

2022-01-11 03:27 UTC, foesa-yang approved these changes

2022-01-11 03:27 UTC, merged