Insert vertex and tag
vesoft-inc/nebula-docs-cn pull request #1360
Opened 2022-01-06 08:13 UTC by foesa-yang

2022-01-06 09:13 UTC, randomJoe211 commented on docs-2.0/1.introduction/2.data-model.md
> +  - 点可以有一个 Tag 或有多个 Tag。也可以没有 Tag。
0到多个Tag？感觉简洁点

2022-01-06 09:13 UTC, randomJoe211 commented on docs-2.0/1.introduction/2.data-model.md
> +  - 点可以有一个 Tag 或有多个 Tag。也可以没有 Tag。
下同

2022-01-06 09:13 UTC, randomJoe211 commented on docs-2.0/20.appendix/0.FAQ.md
> +Nebula Graph {{ nebula.release }} 的数据模型中，设计允许存在"悬挂边"；也没有 openCypher 中的 MERGE 语句。对于悬挂边的保证完全依赖应用层面。详见 [INSERT VERTEX](../3.ngql-guide/12.vertex-statements/1.insert-vertex.md), [DELETE VERTEX](../3.ngql
这段话读起来有些不顺，能重新组织一下语言吗

2022-01-06 09:31 UTC, cangfengzhs commented on docs-2.0/2.quick-start/4.nebula-graph-crud.md
> +    VALUES <vid>: ([, <property_value>...])
There are some error. 
Correct grammar may be like
```
INSERT VERTEX [IF NOT EXISTS] [<tag_list>] VALUES <vertex_list>
<tag_list> ::= <tag> [{ ',' tag }...]
<tag> ::= <tag_name> '(' [<property_name> [{',' <property_name>}...] ] ')'
<vertex_list> ::= <vertex> [ {',' <vertex>}... ]
<vertex> ::= <vid> ':' '(' [<property_value> [{',' <property_value>}...]] ')'
```

2022-01-06 09:35 UTC, cangfengzhs commented on docs-2.0/3.ngql-guide/12.vertex-statements/1.insert-vertex.md
ditto

```
INSERT VERTEX [IF NOT EXISTS] [<tag_list>] VALUES <vertex_list>
<tag_list> ::= <tag> [{ ',' tag }...]
<tag> ::= <tag_name> '(' [<property_name> [{',' <property_name>}...] ] ')'
<vertex_list> ::= <vertex> [ {',' <vertex>}... ]
<vertex> ::= <vid> ':' '(' [<property_value> [{',' <property_value>}...]] ')'
```

2022-01-06 09:37 UTC, cangfengzhs commented on docs-2.0/3.ngql-guide/12.vertex-statements/4.delete-vertex.md
> +DELETE VERTEX <vid> [, <vid> ...] [WITH EDGE];
```
DELETE VERTEX <vid> [ { , <vid> }... ] [WITH EDGE]
```

2022-01-06 09:56 UTC, cangfengzhs commented on docs-2.0/2.quick-start/4.nebula-graph-crud.md
>      [, <tag_name> (<property_name>[, <property_name>...]), ...]
你这个新加的']' 位置就不对。。。它应该放到 VALUES之前

2022-01-06 10:05 UTC, whitewum requested changes

2022-01-06 10:05 UTC, whitewum commented on docs-2.0/1.introduction/2.data-model.md
> -  - 点必须有至少一个 Tag，也可以有多个 Tag。但不能没有 Tag。
这里要加个兼容性提示。这是不兼容

2022-01-06 10:05 UTC, whitewum commented on docs-2.0/20.appendix/0.FAQ.md
> +Nebula Graph {{ nebula.release }} 的数据模型中，由设计允许图中存在“悬挂边“；没有 openCypher 中的 MERGE 语句。对于悬挂边的保证完全依赖应用层面。详见 [INSERT VERTEX](../3.ngql-guide/12.vertex-statements/1.insert-vertex.md), [DELETE VERTEX](../3.ng
“悬挂边“ 引号

2022-01-06 10:05 UTC, whitewum commented on docs-2.0/3.ngql-guide/12.vertex-statements/4.delete-vertex.md
> +DELETE VERTEX <vid> [ { , <vid> }... ] [WITH EDGE];
不需要花括号

2022-01-07 03:52 UTC, whitewum approved these changes

2022-01-07 05:35 UTC, cooper-lzy approved these changes

2022-01-07 05:35 UTC, merged