update match statement
vesoft-inc/nebula-docs-cn pull request #1361
Opened 2022-01-06 08:20 UTC by cooper-lzy

2022-01-06 09:36 UTC, abby-cyber submitted a review, later dismissed

2022-01-06 09:40 UTC, whitewum requested changes

2022-01-06 09:40 UTC, whitewum commented on docs-2.0/3.ngql-guide/1.nGQL-overview/1.overview.md
> -      RETURN type(r) AS Type, v2.name AS Name
在这个文档中加个兼容性提示，然后FAQ里面也说明下。

2022-01-07 03:55 UTC, whitewum approved these changes

2022-01-07 09:34 UTC, randomJoe211 approved these changes

2022-01-07 09:35 UTC, merged