Update nebula-analytics.md
vesoft-inc/nebula-docs-cn pull request #1590
Opened 2022-03-23 06:14 UTC by foesa-yang

2022-03-23 08:23 UTC, whitewum requested changes
This is a really bad design

2022-03-24 09:44 UTC, cooper-lzy approved these changes

2022-03-30 06:04 UTC, cooper-lzy approved these changes

2022-04-01 01:31 UTC, whitewum approved these changes

2022-04-01 01:31 UTC, merged