upgrade-nebula
vesoft-inc/nebula-docs-cn pull request #181
Opened 2021-03-12 09:36 UTC by cooper-lzy

2021-03-12 09:49 UTC, tom-chensf commented on docs-2.0/4.deployment-and-installation/3.upgrade-nebula-graph.md
> +    如果服务异常，请查看目录`/usr/local/nebula_GA/logs`内的meta相关日志排查故障。
add meta log file ，give some example about failed message

2021-03-12 10:18 UTC, whitewum requested changes
Wait a sec. 
Some steps are error-prone.

2021-03-15 07:18 UTC, critical27 commented on docs-2.0/4.deployment-and-installation/3.upgrade-nebula-graph.md
> +    $ sudo usr/local/nebula/scripts/nebula.service stop all
/usr/local/nebula/scripts/nebula.service

2021-03-15 07:18 UTC, critical27 commented on docs-2.0/4.deployment-and-installation/3.upgrade-nebula-graph.md
> +    $ sudo cp -R /usr/local/nebula/data/meta/ /usr/local/nebula_GA/data/meta/
add some description about where `data/meta` is from.

2021-03-15 07:18 UTC, critical27 commented on docs-2.0/4.deployment-and-installation/3.upgrade-nebula-graph.md
> +    --src_db_path=/usr/local/nebula/data/storage/ \
Add some description about where data/storage is from. Add a example when data_path consists of multiple path if necessary.

2021-03-15 07:18 UTC, critical27 commented on docs-2.0/4.deployment-and-installation/3.upgrade-nebula-graph.md
> +    --upgrade_version=1
`upgrade_version` ditto

2021-03-15 07:18 UTC, critical27 commented on docs-2.0/4.deployment-and-installation/3.upgrade-nebula-graph.md
> +7. 启动新版本的Storage服务，并检查服务是否正常。
加句等所有机器升级工具都运行完之类的？

2021-03-15 07:18 UTC, critical27 commented on docs-2.0/4.deployment-and-installation/3.upgrade-nebula-graph.md
> +6. 执行如下命令升级版本。集群部署时，需要在集群中的所有Storage服务节点都执行此命令。
**所有Storage**加粗之类的强调下

2021-03-23 05:37 UTC, closed without merging