add ES function
vesoft-inc/nebula-docs-cn pull request #1886
Opened 2022-06-15 05:42 UTC by cooper-lzy

2022-06-15 07:03 UTC, nevermore3 commented on docs-2.0/3.ngql-guide/6.functions-and-expressions/17.ES-function.md
> +nebula> WITH calles("test/player/1") AS a RETURN a;
arg's format 's  /<indexName>/<typeName>/<id>

2022-06-15 07:04 UTC, nevermore3 commented on docs-2.0/3.ngql-guide/6.functions-and-expressions/17.ES-function.md
> +nebula> WITH calles("test/player/1") AS a MATCH (b:player) WHERE b.player.age == a["_source"]["age"] RETURN b;
dito

2022-06-15 07:06 UTC, nevermore3 commented on docs-2.0/3.ngql-guide/6.functions-and-expressions/17.ES-function.md
> ++---------------------------------------------------+
pls add `callESFile('<filePath>')` to the case

2022-06-15 07:33 UTC, whitewum requested changes
how to prepare data?

2022-06-15 07:33 UTC, whitewum commented on docs-2.0/3.ngql-guide/6.functions-and-expressions/17.ES-function.md
> +关于 ES 语法，请参见 [ES 官方文档](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-your-data.html)。
ES不要简写

2022-06-15 07:57 UTC, whitewum requested changes

2022-06-15 07:57 UTC, whitewum commented on docs-2.0/3.ngql-guide/6.functions-and-expressions/17.ES-function.md
> +calles() 函数可以通过 GET 请求执行复杂的查询语句查询 ES 的数据。
完全看不懂，用个逗号分割两句话吧。。。。

2022-06-22 09:45 UTC, whitewum approved these changes

2022-06-24 06:45 UTC, whitewum approved these changes

2022-06-29 02:00 UTC, abby-cyber commented on docs-2.0/3.ngql-guide/6.functions-and-expressions/17.ES-function.md
> +- 兼容 Elasticsearch 7及以上版本，更低版本未测试。
```suggestion
- 兼容 Elasticsearch 7 及以上版本，更低版本未测试。
```

2022-06-29 02:05 UTC, abby-cyber commented on docs-2.0/4.deployment-and-installation/6.deploy-text-based-index/1.text-based-index-restrictions.md
> +- 写入数据时，Elastic Search 会自动创建相应的索引。在 Nebula Graph 中创建全文索引，但是未写入数据，查询时会报错`text search not found`。
```suggestion
- 写入数据时，Elasticsearch 会自动创建相应的索引。在 Nebula Graph 中创建全文索引，但是未写入数据，查询时会报错`text search not found`。
```

2022-06-29 02:05 UTC, abby-cyber commented on docs-2.0/4.deployment-and-installation/6.deploy-text-based-index/1.text-based-index-restrictions.md
> +- 写入数据时，Elastic Search 会自动创建相应的索引。在 Nebula Graph 中创建全文索引，但是未写入数据，查询时会报错`text search not found`。
Elastic Search--->Elasticsearch?

2022-06-29 02:05 UTC, abby-cyber commented on docs-2.0/4.deployment-and-installation/6.deploy-text-based-index/1.text-based-index-restrictions.md
>  - 不支持修改 Elastic Search 中的索引，只能删除重建。
```suggestion
- 不支持修改 Elasticsearch 中的索引，只能删除重建。
```

2022-06-29 02:05 UTC, abby-cyber commented on mkdocs.yml
> +#          - Elasticsearch 查询函数: 3.ngql-guide/6.functions-and-expressions/17.ES-function.md
why do we hide this doc?

2022-06-30 02:36 UTC, abby-cyber approved these changes

2022-06-30 06:44 UTC, foesa-yang approved these changes

2022-06-30 06:44 UTC, merged