add faq for dag
vesoft-inc/nebula-docs-cn pull request #1930
Opened 2022-07-01 06:26 UTC by cooper-lzy

2022-07-05 07:03 UTC, foesa-yang submitted a review, later dismissed

2022-07-05 08:02 UTC, whitewum requested changes

2022-07-05 08:02 UTC, whitewum commented on docs-2.0/graph-computing/0.deploy-controller-analytics.md
> +Dag Controller 包含图查询组件和图计算组件。图查询是发送请求给 Graph 进程进行单线程查询，因此只能增大 Graph 服务的内存进行加速；图计算是由 Nebula Analytics 提供的分布式节点进行计算，可以增大计算集群规模进行加速。
图查询是发送请求给 Graph 进程进行查询

2022-07-05 08:02 UTC, whitewum commented on docs-2.0/graph-computing/0.deploy-controller-analytics.md
> +Dag Controller 服务仅仅提供调度功能，不会崩溃，但是数据量过大可能会导致 Nebula Analytics 服务将数据写入到 HDFS 或者 Nebula Graph 时内存不足而崩溃。
Dag Controller 服务仅仅提供调度功能，不会崩溃，但是数据量过大可能会导致 Nebula Analytics 服务将数据写入到或者读取 HDFS 或者 Nebula Graph 时出现内存不足。

2022-07-13 06:22 UTC, randomJoe211 approved these changes

2022-07-13 06:41 UTC, whitewum approved these changes

2022-07-13 06:41 UTC, merged