Update enterprise in docs
vesoft-inc/nebula-docs-cn pull request #1939
Opened 2022-07-04 10:28 UTC by foesa-yang

2022-07-04 10:53 UTC, randomJoe211 commented on docs-2.0/7.data-security/1.authentication/2.management-user.md
> +  CREATE USER [IF NOT EXISTS] <user_name> [WITH PASSWORD '<password>'][WITH IP WHITELIST <ip_list>];
显示企业版的时候，社区版的参数说明是看不见的，但企业版里也需要这些内容，一起带下来吧

2022-07-04 10:53 UTC, randomJoe211 commented on mkdocs.yml
> +        # 文档为企业版需注释以下页面（以下文档均为企业版）
原句不太通顺
发布包含企业版功能的文档版本时，注释以下页面

2022-07-04 10:53 UTC, randomJoe211 commented on mkdocs.yml
> +    ent_begin: <!-- # 文档为企业版时需补全该注释
```suggestion
    ent_begin: <!-- # 文档包含企业版时需补全该注释（<!-- -->），只包含社区版时只保留注释头（<!--）
```

2022-07-04 10:53 UTC, randomJoe211 commented on mkdocs.yml
> +    ent_end: -->
```suggestion
    ent_end: --> #文档包含企业版时需补全该注释（<!-- -->），只包含社区版时只保留注释尾（-->）
```

2022-07-04 10:53 UTC, randomJoe211 commented on mkdocs.yml
> +    commu_end: <!-- -->
同上，注释写清楚点以后不容易出错

2022-07-04 10:53 UTC, randomJoe211 commented on mkdocs.yml
> +#  - Nebula Dashboard（企业版）:
要确认一下Dashboard企业版发不发兼容3.2.0社区版的版本，如果发，这里要保留，如果不发，可以隐藏
其它周边产品也是类似

2022-07-05 03:24 UTC, cooper-lzy approved these changes

2022-07-05 03:31 UTC, abby-cyber commented on docs-2.0/20.appendix/6.eco-tool-version.md
>  ## Nebula Dashboard（企业版）
is there any problem if we add macro for dashboard enterprise edition and explorer, since we release these two products.

2022-07-05 06:46 UTC, whitewum requested changes

2022-07-05 06:46 UTC, whitewum commented on docs-2.0/5.configurations-and-logs/1.configurations/2.meta-config.md
> +
单独把license_path 搞成一个表格就行了。不要多加一个 commu 吧？

2022-07-05 06:46 UTC, whitewum commented on docs-2.0/7.data-security/1.authentication/2.management-user.md
> +
{{{ ent.ent_begin}}}
```ngql
ALTER USER <user_name> WITH PASSWORD '<password>';
```
{{{ ent.ent_end}}}
应该这样就行了

2022-07-05 06:46 UTC, whitewum commented on docs-2.0/nebula-operator/3.deploy-nebula-graph-cluster/3.1create-cluster-with-kubectl.md
> +{{ ent.ent_begin }}
不要大片重复代码，这样维护会有很多问题的。

2022-07-05 06:46 UTC, whitewum commented on mkdocs.yml
> +        # 发布包含企业版功能的文档版本时，注释以下页面
用一个 begin end包裹要注释的

2022-07-05 06:46 UTC, whitewum commented on mkdocs.yml
> +  commu:
不要这个。只保留一个ent

2022-07-05 08:48 UTC, foesa-yang commented on docs-2.0/5.configurations-and-logs/1.configurations/2.meta-config.md
> +
社区版和企业版的内容是不一样的，单独把license_path 搞成一个表格看起来会有点丑

2022-07-05 08:48 UTC, foesa-yang commented on docs-2.0/7.data-security/1.authentication/2.management-user.md
> +
社区版和企业版的语法不通，白名单只有企业版才有

2022-07-05 08:49 UTC, foesa-yang commented on mkdocs.yml
> +        # 发布包含企业版功能的文档版本时，注释以下页面
这个部分是yaml文件，begin和end的宏放在这里会有点问题

2022-07-05 08:53 UTC, foesa-yang commented on docs-2.0/7.data-security/1.authentication/2.management-user.md
> +
如果只包围语句部分，我在本地跑了一下，二级列表会出现格式问题

2022-07-06 02:21 UTC, cooper-lzy approved these changes

2022-07-07 04:24 UTC, whitewum approved these changes

2022-07-07 04:24 UTC, merged