Lookup statement
vesoft-inc/nebula-docs-cn pull request #217
Opened 2021-03-25 10:03 UTC by cooper-lzy

2021-03-25 11:12 UTC, whitewum requested changes
why delete reduce函数?

2021-03-26 01:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vesoft-inc/nebula-docs-cn?pullRequest=217) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vesoft-inc/nebula-docs-cn?pullRequest=217) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vesoft-inc/nebula-docs-cn?pullRequest=217) it.</sub>

2021-03-26 03:19 UTC, randomJoe211 approved these changes

2021-03-26 03:23 UTC, bright-starry-sky commented
👍

2021-03-26 03:24 UTC, bright-starry-sky approved these changes

2021-03-29 04:28 UTC, whitewum approved these changes

2021-03-29 04:28 UTC, merged