modify tagless
vesoft-inc/nebula-docs-cn pull request #2192
Opened 2022-10-10 06:58 UTC by foesa-yang

2022-10-10 08:05 UTC, cooper-lzy commented on docs-2.0/3.ngql-guide/10.tag-statements/2.drop-tag.md
> +    在 NebulaGraph 3.x 版本中，允许存在无 Tag 的点，但在 NebulaGraph {{nebula.release}} 中默认不支持无 Tag 的点。如需使用无 Tag 的点要在集群内所有 Graph 服务的配置（`nebula-graphd.conf`）中新增`--graph_use_vertex_key=true`；在所有 Storage 服务的配置（`nebula
```suggestion
    在 NebulaGraph 3.2.1 之前的版本中，允许存在无 Tag 的点，但从 NebulaGraph 3.3.0 开始默认不支持无 Tag 的点。如需使用无 Tag 的点要在集群内所有 Graph 服务的配置（`nebula-graphd.conf`）中新增`--graph_use_vertex_key=true`；在所有 Storage 服务的配置（`nebula-storaged.conf`）中新增`--use_vertex_key=true`。
```

2022-10-10 11:03 UTC, whitewum submitted a review, later dismissed

2022-10-12 08:51 UTC, randomJoe211 commented on docs-2.0/3.ngql-guide/10.tag-statements/2.drop-tag.md
> +    在 NebulaGraph 3.2.1 之前的版本中，允许存在无 Tag 的点，但从 NebulaGraph 3.3.0 开始默认不支持无 Tag 的点。如需使用无 Tag 的点要在集群内所有 Graph 服务的配置（`nebula-graphd.conf`）中新增`--graph_use_vertex_key=true`；在所有 Storage 服务的配置（`nebula-storag
```suggestion
    在 NebulaGraph 3.2.1 之前的版本中，允许存在无 Tag 的点，但从 NebulaGraph 3.3.0 开始默认不支持无 Tag 的点。如需使用无 Tag 的点，在集群内所有 Graph 服务的配置文件（`nebula-graphd.conf`）中新增`--graph_use_vertex_key=true`；在所有 Storage 服务的配置文件（`nebula-storaged.conf`）中新增`--use_vertex_key=true`。
```

2022-10-12 08:51 UTC, randomJoe211 commented on docs-2.0/3.ngql-guide/12.vertex-statements/1.insert-vertex.md
> +        NebulaGraph 3.3.0 中默认不支持插入无 Tag 的点。如需使用无 Tag 的点要在集群内所有 Graph 服务的配置（`nebula-graphd.conf`）中新增`--graph_use_vertex_key=true`；在所有 Storage 服务的配置（`nebula-storaged.conf`）中新增`--use_vertex_key=true`。命令
```suggestion
        NebulaGraph 3.3.0 中默认不支持插入无 Tag 的点。如需使用无 Tag 的点，在集群内所有 Graph 服务的配置文件（`nebula-graphd.conf`）中新增`--graph_use_vertex_key=true`；在所有 Storage 服务的配置文件（`nebula-storaged.conf`）中新增`--use_vertex_key=true`。插入无 Tag 点的命令示例如`INSERT VERTEX VALUES "1":();`。
```

2022-10-12 08:51 UTC, randomJoe211 approved these changes

2022-10-20 02:08 UTC, abby-cyber submitted a review, later dismissed

2022-10-20 06:22 UTC, shanlai approved these changes

2022-10-20 06:38 UTC, cooper-lzy submitted a review, later dismissed

2022-10-20 10:29 UTC, whitewum requested changes

2022-10-20 10:29 UTC, whitewum commented on docs-2.0/3.ngql-guide/10.tag-statements/2.drop-tag.md
> +    NebulaGraph 3.3.0 中默认不支持插入无 Tag 的点。如需使用无 Tag 的点，在集群内所有 Graph 服务的配置文件（`nebula-graphd.conf`）中新增`--graph_use_vertex_key=true`；在所有 Storage 服务的配置文件（`nebula-storaged.conf`）中新增`--use_vertex_key=true`。
use macro

2022-10-20 10:29 UTC, whitewum commented on docs-2.0/3.ngql-guide/12.vertex-statements/1.insert-vertex.md
> +        NebulaGraph 3.3.0 中默认不支持插入无 Tag 的点。如需使用无 Tag 的点，在集群内所有 Graph 服务的配置文件（`nebula-graphd.conf`）中新增`--graph_use_vertex_key=true`；在所有 Storage 服务的配置文件（`nebula-storaged.conf`）中新增`--use_vertex_key=true
use macro
maybe next version tagless is supported again

2022-10-24 02:09 UTC, abby-cyber approved these changes

2022-10-27 02:26 UTC, merged