add-bbox-overview
vesoft-inc/nebula-docs-cn pull request #2216
Opened 2022-10-17 12:51 UTC by abby-cyber

2022-10-18 01:19 UTC, cooper-lzy commented on docs-2.0/6.monitor-and-metrics/3.bbox/3.1.bbox.md
> +- 当无法自行解决问题时，用户可以使用以下命令将文件打包发送给 NebulaGraph 官方，以便官方分析问题。
这里说发送给官方，最好说一下途径，论坛还是销售邮箱

2022-10-18 01:53 UTC, Shylock-Hg commented on docs-2.0/6.monitor-and-metrics/3.bbox/3.1.bbox.md
> +黑匣子功能默认开启，系统会在 NebulaGraph 首次启动时在其安装目录下自动创建一个名为`black_bbox`的目录，用于存储收集的指标数据。
`black_box`

2022-10-18 02:23 UTC, whitewum requested changes

2022-10-18 02:23 UTC, whitewum commented on docs-2.0/6.monitor-and-metrics/3.bbox/3.1.bbox.md
> +- 当无法自行解决问题时，用户可以使用以下命令将文件打包并通过邮箱（inquiry@vesoft.com）发送给 NebulaGraph 官方，以便官方分析问题。
不能这样子，让PD想个靠谱点的办法，不然一堆白嫖的

2022-10-20 02:12 UTC, randomJoe211 approved these changes

2022-10-20 06:01 UTC, cooper-lzy approved these changes

2022-10-20 06:04 UTC, foesa-yang approved these changes

2022-10-20 06:15 UTC, whitewum approved these changes

2022-10-20 06:15 UTC, merged