tips-for-no-uppercase-letters-in-fulltext-index-name-
vesoft-inc/nebula-docs-cn pull request #2229
Opened 2022-10-19 09:58 UTC by abby-cyber

2022-10-20 02:45 UTC, randomJoe211 approved these changes

2022-10-20 10:26 UTC, whitewum requested changes

2022-10-20 10:26 UTC, whitewum commented on docs-2.0/4.deployment-and-installation/6.deploy-text-based-index/1.text-based-index-restrictions.md
>  全文索引有如下 16 条限制：
17

2022-10-27 02:13 UTC, cooper-lzy approved these changes

2022-10-27 02:14 UTC, cooper-lzy commented on docs-2.0/4.deployment-and-installation/6.deploy-text-based-index/1.text-based-index-restrictions.md
>  全文索引有如下 16 条限制：
```suggestion
全文索引有如下 20 条限制：
```

2022-10-27 02:25 UTC, whitewum approved these changes

2022-10-27 02:26 UTC, merged