Update tagless configuration
vesoft-inc/nebula-docs-cn pull request #2231
Opened 2022-10-20 05:45 UTC by cooper-lzy

2022-10-20 06:29 UTC, abby-cyber approved these changes

2022-10-20 10:25 UTC, whitewum requested changes

2022-10-20 10:25 UTC, whitewum commented on docs-2.0/nebula-exchange/parameter-reference/ex-ug-parameter.md
> +    NebulaGraph 默认不支持无 Tag 的点。如果需要导入无 Tag 的点，需要先在集群内开启[支持无 Tag 点](../..//3.ngql-guide/12.vertex-statements/1.insert-vertex.md)，然后在 Exchange 的配置文件内新增`nebula.enableTagless`参数，值为`true`。示例如下：
Nebula Graph {{ nebula.release }} 默认不支持无 Tag 的点

2022-10-24 08:42 UTC, whitewum approved these changes

2022-10-27 02:25 UTC, merged