opt-desc-for-max_sessions_per_ip_per_user
vesoft-inc/nebula-docs-cn pull request #2484
Opened 2023-01-13 03:06 UTC by abby-cyber

2023-01-13 04:19 UTC, wey-gu requested changes

2023-01-13 04:19 UTC, wey-gu commented on docs-2.0/5.configurations-and-logs/1.configurations/3.graph-config.md
> +|`max_sessions_per_ip_per_user`|`300` | 相同用户和 IP 地址可以创建的最大活跃会话数。|
我觉得这里的描述（包括英文文档中）是不准确的，不是可以创建的，而是当前可用的，现在的描述会让人一位历史创建过的然后关闭的 session 也受这个限制

https://github.com/vesoft-inc/nebula/discussions/5250

2023-01-13 04:20 UTC, wey-gu commented
如上 review，我们要同步改写英文文档，可以参考 https://github.com/vesoft-inc/nebula/discussions/5250 中 @porscheme 的描述 open sessions per user/ip combination

- [ ] en docs

2023-01-13 04:24 UTC, wey-gu commented on docs-2.0/5.configurations-and-logs/1.configurations/3.graph-config.md
> +|`max_sessions_per_ip_per_user`|`300` | 相同用户和 IP 地址可以创建的最大活跃会话数。|
啊，我才意识到你是因为这个 discussion 才创建的 PR，我觉得这个表达也是可以的。

2023-01-13 04:25 UTC, wey-gu commented on docs-2.0/5.configurations-and-logs/1.configurations/3.graph-config.md
> +|`max_sessions_per_ip_per_user`|`300` | 相同用户和 IP 地址可以创建的最大活跃会话数。|
可是我请求了你做变更，似乎不知道怎么取消这个请求了😭

2023-01-13 05:17 UTC, wey-gu approved these changes

2023-01-17 07:48 UTC, randomJoe211 approved these changes

2023-01-17 07:48 UTC, merged