BLANCE and Case sensitivity
vesoft-inc/nebula-docs-cn pull request #258
Opened 2021-04-01 07:48 UTC by cooper-lzy

2021-04-01 08:29 UTC, randomJoe211 requested changes

2021-04-01 08:29 UTC, randomJoe211 commented on docs-2.0/8.service-tuning/load-balance.md
> +如果需要调整Nebula Graph的Storage服务规模，请使用`BALANCE`语句。
这句不合适，请根据https://github.com/vesoft-inc/nebula-docs/pull/411 改一下

2021-04-02 02:46 UTC, whitewum commented on docs-2.0/3.ngql-guide/20.appendix/identifier-case-sensitivity.md
> +以下语句是等价的，因为`show`和`paces`是关键字。
spaces

2021-04-06 02:36 UTC, cooper-lzy commented
https://github.com/vesoft-inc/nebula-docs-cn/pull/266

2021-04-06 02:36 UTC, closed without merging