appendix
vesoft-inc/nebula-docs-cn pull request #259
Opened 2021-04-01 10:08 UTC by cooper-lzy

2021-04-01 10:14 UTC, randomJoe211 commented on docs-2.0/3.ngql-guide/20.appendix/vid-partition.md
> +- 如果图中的点少于10亿个，可以调用`hash()`函数生成64位整数的`VID`。
删掉，2.0不需要用这招了

2021-04-02 02:42 UTC, whitewum requested changes

2021-04-02 02:42 UTC, whitewum commented on docs-2.0/3.ngql-guide/20.appendix/vid-partition.md
> +- C++示例
不对。这个不是C++ 示例。

2021-04-02 02:42 UTC, whitewum commented on docs-2.0/3.ngql-guide/20.appendix/vid-partition.md
> +- C示例
这个不是C示例，删掉。

2021-04-06 02:32 UTC, cooper-lzy commented
https://github.com/vesoft-inc/nebula-docs-cn/pull/265/files

2021-04-06 02:32 UTC, cooper-lzy commented
https://github.com/vesoft-inc/nebula-docs-cn/pull/265/files

2021-04-06 02:32 UTC, closed without merging