add path faq
vesoft-inc/nebula-docs-cn pull request #584
Opened 2021-06-04 08:23 UTC by cooper-lzy

2021-06-04 08:26 UTC, FengUyu submitted a review, later dismissed

2021-06-04 09:15 UTC, whitewum requested changes

2021-06-04 09:15 UTC, whitewum commented on docs-2.0/20.appendix/0.FAQ.md
> +5跳查询时，都会查询到点C，6跳查询时，`GO`语句会查询到点D，因为边可以重复查询，而`MATCH`语句查询为空，因为边不可以重复。
要说明 1->2->3->4->5->6 这样

2021-06-07 04:34 UTC, whitewum submitted a review, later dismissed

2021-06-07 06:24 UTC, randomJoe211 approved these changes

2021-06-07 07:18 UTC, randomJoe211 approved these changes

2021-06-07 08:33 UTC, whitewum approved these changes

2021-06-08 01:55 UTC, FengUyu approved these changes

2021-06-08 01:55 UTC, merged