add EMPTY
vesoft-inc/nebula-docs-cn pull request #624
Opened 2021-06-21 07:41 UTC by cooper-lzy

2021-06-21 08:14 UTC, whitewum requested changes
Let's wait a sec to test more cases.

2021-06-21 10:14 UTC, FengUyu approved these changes

2021-06-22 08:25 UTC, whitewum commented on docs-2.0/3.ngql-guide/5.operators/1.comparison.md
> +nebula> GO FROM "player100" OVER * WHERE $$.player.name IS NOT EMPTY YIELD follow._dst;
I think it is better to add to `GO`-syntax

2021-06-23 02:34 UTC, whitewum approved these changes

2021-06-23 02:39 UTC, randomJoe211 approved these changes

2021-06-23 02:39 UTC, merged