Update 1.resource-preparations.md
vesoft-inc/nebula-docs-cn pull request #663
Opened 2021-06-30 01:54 UTC by cooper-lzy

2021-06-30 02:03 UTC, FengUyu approved these changes

2021-06-30 05:12 UTC, whitewum requested changes
sudo chmod a+w /opt
sudo chmod -R a+w /opt/vesoft-inc/

2021-07-01 09:50 UTC, whitewum approved these changes

2021-07-01 09:53 UTC, randomJoe211 approved these changes

2021-07-01 09:53 UTC, merged