datasource add clickhouse and maxcompute
vesoft-inc/nebula-docs-cn pull request #794
Opened 2021-08-03 08:05 UTC by cooper-lzy

2021-08-03 08:09 UTC, Nicole00 commented on docs-2.0/nebula-exchange/ex-ug-compile.md
>  1. 克隆仓库`nebula-java`。
client都有发版本，不需要安装Nebula Java 这一步了

2021-08-03 08:19 UTC, Nicole00 commented on docs-2.0/nebula-exchange/use-exchange/ex-ug-import-from-clickhouse.md
> +- ClickHouse：21.7.5.29
这个版本是怎么来啊，我测的环境是 docker部署的，镜像是yandex/clickhouse-server latest tag。

2021-08-03 08:25 UTC, Nicole00 commented
建议在 导入命令文档中加上 如果使用yarn-cluster模式进行任务提交的说明，参考readme https://github.com/vesoft-inc/nebula-spark-utils/tree/master/nebula-exchange

2021-08-03 09:31 UTC, whitewum reviewed
如果是支持2.0.1内核的，直接向v2.0.1branch发pull request
内核的2.5.0和2.0.1会有很多不同和不兼容
这个部分pr cherrypick过来，文件注释掉

2021-08-03 09:31 UTC, whitewum commented on docs-2.0/nebula-exchange/about-exchange/ex-ug-what-is-exchange.md
> +Exchange 2.1新增支持[ClickHouse](../use-exchange/ex-ug-import-from-clickhouse.md)和[MaxCompute](../use-exchange/ex-ug-import-from-maxcompute.md)，同时兼容以上数据格式和来源。
use macro, not hardcode.

- 支持[ClickHouse](../use-exchange/ex-ug-import-from-clickhouse.md)和[MaxCompute](../use-exchange/ex-ug-import-from-maxcompute.md)，同时兼容以上数据格式和来源。

2021-08-03 09:31 UTC, whitewum commented on docs-2.0/nebula-exchange/ex-ug-compile.md
>  本文介绍如何编译Nebula Exchange。用户也可以直接[下载](https://repo1.maven.org/maven2/com/vesoft/nebula-exchange/2.0.0/)编译完成的`.jar`文件。
2.0.0？？？？

2021-08-03 09:31 UTC, whitewum commented on docs-2.0/nebula-exchange/ex-ug-compile.md
> +### 安装Nebula Java Client 2.0.0
2.0.0？？？？

2021-08-03 09:31 UTC, whitewum commented on docs-2.0/nebula-exchange/ex-ug-compile.md
>          安装后在本地Maven仓库会生成JAR文件，例如`com/vesoft/client/2.0.0/client-2.0.0.jar`。
2.0.0

2021-08-03 09:38 UTC, whitewum requested changes
统一一下jar的版本号
必须和内核对齐。
master是2.5.0，不要向master提交2.0.1内核的内容。

2021-08-11 01:28 UTC, Nicole00 commented on docs-2.0/nebula-exchange/about-exchange/ex-ug-limitations.md
>  Exchange client版本（即JAR包版本）和Nebula Graph的版本对应关系如下。
Nebula  Exchange版本， 产品名是Nebula Exchange

2021-08-11 01:30 UTC, Nicole00 commented on docs-2.0/nebula-exchange/ex-ug-compile.md
> +- 修改Maven安装目录下`libexec/conf/settings.xml`文件的`mirror`部分：
这部分不是必须的，有的用户自己设置的mirror有问题所以会出现编译的问题，可以迁移到FAQ中。

2021-08-11 01:33 UTC, Nicole00 commented on docs-2.0/nebula-exchange/use-exchange/ex-ug-import-from-clickhouse.md
> +      # vertex.field的值必须与上述fields中的列名保持一致。
vertex.field的值与 fields中的列名没关系。 要求是：vertex.field的值必须存在于sentence 查询结果中

2021-08-11 01:35 UTC, Nicole00 commented on docs-2.0/nebula-exchange/use-exchange/ex-ug-import-from-csv.md
>        # 不要使用vertex.policy映射。
为什么不要使用policy映射啊？

2021-08-11 01:39 UTC, Nicole00 commented
建议文档中的192.168.*.*这类表示ip的 可以统一使用127.0.0.1

2021-08-11 02:25 UTC, whitewum submitted a review, later dismissed

2021-08-11 02:25 UTC, whitewum commented on docs-2.0/nebula-exchange/use-exchange/ex-ug-import-from-hbase.md
> +      # 单次写入 Nebula Graph 的最大数据条数。
单批次写入 Nebula Graph 的数据条数

2021-08-11 02:25 UTC, whitewum commented on docs-2.0/nebula-exchange/use-exchange/ex-ug-import-from-hbase.md
> +      # 单次写入 Nebula Graph 的最大数据条数。
ditto

2021-08-11 02:37 UTC, foesa-yang submitted a review, later dismissed

2021-08-11 02:51 UTC, randomJoe211 approved these changes

2021-08-11 02:51 UTC, merged