show meta leader
vesoft-inc/nebula-docs-cn pull request #939
Opened 2021-09-08 07:38 UTC by cooper-lzy

2021-09-08 07:44 UTC, foesa-yang submitted a review, later dismissed

2021-09-08 09:58 UTC, randomJoe211 requested changes

2021-09-08 09:58 UTC, randomJoe211 commented on docs-2.0/3.ngql-guide/7.general-query-statements/6.show/19.show-meta-leader.md
> +`SHOW META LEADER`语句显示当前Meta集群的ledaer信息。
leader, typo

2021-09-08 09:58 UTC, randomJoe211 commented on docs-2.0/3.ngql-guide/7.general-query-statements/6.show/19.show-meta-leader.md
> +    仅企业版2.5.0支持该命令，社区版将在2.6.0版本支持该命令。
未来的可能要写吗？万一不上了呢

2021-09-08 09:58 UTC, randomJoe211 commented on docs-2.0/3.ngql-guide/7.general-query-statements/6.show/19.show-meta-leader.md
> +|`Meta Leader`|Meta集群的ledaer信息，包括leader所在服务器的IP地址和端口。|
leader

2021-09-08 10:05 UTC, cooper-lzy commented on docs-2.0/3.ngql-guide/7.general-query-statements/6.show/19.show-meta-leader.md
> +    仅企业版2.5.0支持该命令，社区版将在2.6.0版本支持该命令。
社区版master已经支持了，不会在2.6.0下掉吧？要不要评估下？

2021-09-09 01:03 UTC, randomJoe211 approved these changes

2021-09-10 02:00 UTC, foesa-yang approved these changes

2021-09-10 02:00 UTC, merged